print("Seja Bem-Vindo!")
print("\n")
print("Escolha sua Cantina:")
print("\n")
print("1 - UMP - União de Mocidade Presbiteriana")
print("2 - UPH - União Presbiteriana de Homens")
print("3 - UPA - União Presbiteriana de Adolecentes")
print("4 - SAF - Sociedade Auxiliadora Feminina")